[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "857204c790397c17416a28e6dfb8dc4202ae3ae7"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "be582c8c824b9f25df350e6704e76b1c6a97ebbf89eb598784e907dc7eadc3af"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-v2.17.7-x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "0276e05729b40ed2585c410f4e5550190ebb19da"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "fe4a5b4b1b16703cbb4a53e770aaa647da77ef72b7f1125c69a199528256c4c3"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-v2.17.7-i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "9732b83c697e8ac666473c9943bcbbf14c74c95d"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "7a6418a6f13a97a42a32c0aa1e826cdae12e80989ae2114233b59807a697a5d5"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-v2.17.7-powerpc64le-linux-gnu.tar.gz"

[[Glibc-build_log]]
arch = "x86_64"
git-tree-sha1 = "6f4de9edaeea674b87b8163717df5bd8bb39903f"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "0766dd8e5202a39af5051211b6a8a39b7aea5c30e9305c66bcc71cd518c9ab88"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-build_log-v2.17.7-x86_64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "i686"
git-tree-sha1 = "f25c148a97513e771e1dca067fc9c1b56d60969b"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "42dd3d2eb75b0734a96e9b6fd85d20067ede3384422fc7148f44f7fe60701ef4"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-build_log-v2.17.7-i686-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "3064b434c0ab2b3c78a219d454bff69c419e13cb"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "d52552042b237ce4fe6666fc9141e57937452fa40507256f3068aff998744cb4"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-build_log-v2.17.7-powerpc64le-linux-gnu.tar.gz"

[[Glibc-extract_log]]
arch = "x86_64"
git-tree-sha1 = "5de0d2d5fa1ddd35d290d73571c0d8b6304dc268"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "4ac6bdd099283378bb34aa61fd0e1c5f1c6f856e2b61031a59867559c45bc2cc"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-extract_log-v2.17.7-x86_64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "i686"
git-tree-sha1 = "db89abc905b15a8a03c083913e1b3580dbbdddf6"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "012455b06029c9a4c84cb41f5d5829a6287a98bc29af437d4c5ec7bd5cde6c7c"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-extract_log-v2.17.7-i686-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "47024253bf10104b1b53a50fc06116bc789dca20"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "6dc226aa76e915449d3b258fc6ad901dce36293f4d739aaea5e14e7fa976b008"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-extract_log-v2.17.7-powerpc64le-linux-gnu.tar.gz"
