[[Glibc]]
arch = "i686"
git-tree-sha1 = "a4d51b17dcc180f7b33ad2a687c3801ab92d3ff2"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "f5fb7f47f97f3a729df71982d719baded71a5f080734829d760f99311b3b2714"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/Glibc-v2.12.2+5/Glibc.v2.12.2.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "8acbc0f911d31c5d06ae0bfcabe41cf420ca3044"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "0f5f31a2742424788ce6e4e0ececbdd8f4955f5303d0e68eab32f6818d3bda84"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/Glibc-v2.12.2+5/Glibc.v2.12.2.x86_64-linux-gnu.tar.gz"
