[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "6432c5b4bd642c8dc10d4db872dc8a13e09f0ba8"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "ddb5549580b2f31329926d65c6ef64dd235cefacad5a5c72b1444070f2306a7b"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-v2.19.2-x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "da6aa1be6facf08303e9bfe57fbe4035016e74f2"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "ea503f6fbe05ad2bff7647f9df73421c60c0a8a20561022c58926add9d4940bd"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-v2.19.2-i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "95b433ee4bd35f23bfa945467abd8159946f13d2"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "b9e682c53dc725421aa1c522f03bea429527a6ec5790ac58748346bf7d82660e"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-v2.19.2-armv7l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1742a98e32329610ff3d2cdc20c50edbb2470c17"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "c1f416a98fce44cd874b0a56b5941985878c887a6df034a0fbe10eeceff83e01"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-v2.19.2-armv6l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "aarch64"
git-tree-sha1 = "215b1a6bbb2efb7d4d05acacda6d8627cb3b8f19"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "5aa9eee9e8e581e90c238f9510f0e9dbfce6174305005165c4a33533ae772b7b"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-v2.19.2-aarch64-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "c27d35022a9cc07bff83a630962d2c3157bd2c10"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "6df78f7278cfbe820e19b89323e3a3ac04848cf689af380b00168707b957b0c1"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-v2.19.2-powerpc64le-linux-gnu.tar.gz"

[[Glibc-build_log]]
arch = "x86_64"
git-tree-sha1 = "623f13b6f5ad71d0be45933321891c58967b3170"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "f6a4ce7663871586839a29b6940349dc5d032f670846fb760cb448f9ac4af662"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-build_log-v2.19.2-x86_64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "i686"
git-tree-sha1 = "9f59aca5244907d6c1743bf8032f0fe08d571fc6"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "110c8a50d2bf01553358c948967cb3707a1fa2127bc2f68c368b7b4c9224eb1b"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-build_log-v2.19.2-i686-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1599c1c9d705e5cf9933811a68a86952c36cd618"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "80fd180895d0af7b7c1916c6a4ec62b068b0acf0b79faab63202b7a49db4e83c"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-build_log-v2.19.2-armv7l-linux-gnueabihf.tar.gz"
[[Glibc-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6e1f972260199670f3c82b582c4f118bd54dae6d"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "d3c9e3238cdf6bce93eea70c9fdd26bf3308024ebbcdb397642fad953a7eeb60"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-build_log-v2.19.2-armv6l-linux-gnueabihf.tar.gz"
[[Glibc-build_log]]
arch = "aarch64"
git-tree-sha1 = "6323ab971f492788235249069a07cbbdb94f0b52"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "16601eb34fbc88166aa4813e87ce538e233b534bc2d758866e8cb810ee6540f6"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-build_log-v2.19.2-aarch64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "540259fee4d604889f6cda7cadf98de63be453cd"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "4901f740730ca8e9b3a2933e88fdc4c80a3c0af0e9f76c038bcefae5ad308173"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-build_log-v2.19.2-powerpc64le-linux-gnu.tar.gz"

[[Glibc-extract_log]]
arch = "x86_64"
git-tree-sha1 = "94d403d1f835a215bbcff95543842309474e2fa3"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "9d8934e0bb4cf2b3b5d8bc54e88a3ad734ad4c0605137ea7df446e9700ca7c82"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-extract_log-v2.19.2-x86_64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "i686"
git-tree-sha1 = "8bd73424420beacec7b8f69989fee66cefa9549f"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "3cc67aece0034ca76faf9e31f3ae08441f51b2ea13246a0dc4f1ae09339bf4eb"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-extract_log-v2.19.2-i686-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "040c81b9abdf49fb74e2f537831d1ec180cfbef8"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "ae2643d2ca079203411fb01594f0c136926c237ba1cbed87cf186ac8277b517e"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-extract_log-v2.19.2-armv7l-linux-gnueabihf.tar.gz"
[[Glibc-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f32dc9d6f437f408632c839f36c9c4ef901c38e3"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "5af31b09c0c4ab701c00d7cbbebf5f189e7d4c55619f25ee4b8d1c2dcbf94a98"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-extract_log-v2.19.2-armv6l-linux-gnueabihf.tar.gz"
[[Glibc-extract_log]]
arch = "aarch64"
git-tree-sha1 = "4de3ed09372408e7e24139a530208000b0ebc1b7"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "4a3d4cca034ad5a32f3fe2f33e5f3547d6d71cb9be8aad831439db37a5789da6"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-extract_log-v2.19.2-aarch64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "8d4eb7cb1fc3b7292a2a9f10023dfdf4c9e729a4"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "597bdc0df4eb1918e22c91e476401da50474d72bc8e83cdb7559d29aa5021c0f"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.2-GCC/Glibc-extract_log-v2.19.2-powerpc64le-linux-gnu.tar.gz"
