[[Glibc]]
arch = "i686"
git-tree-sha1 = "f5b95a83becddc064df1894b8c14da018be38b50"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "c50eaaeb473a7d2d589b928757c2c16b21a3bb3b3be78b315f4e82d6feb5068b"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/Glibc-v2.12.2+2/Glibc.v2.12.2.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "89214576c783dc7eda80d4e35fbc7924aae3f5d0"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "c7b176c5ca12b2a23cc6f0458a5a01c14c1c6c0693dd8291e4029ed38f63be7d"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/Glibc-v2.12.2+2/Glibc.v2.12.2.x86_64-linux-gnu.tar.gz"
