[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "963900af8f086e1870a6ded028038409d33e964d"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "3309598d2a4085fff990db73eafbb24cdee063b15d6011937c9bd4ca85bb59da"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-v2.19.1-x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "20c630c45193a45f96ef8b457f9c0613cbd8dd4a"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "ed001ec3cb85323b8ee2c2c16e7476f307d16fb8d934403719f56435db9e6dfd"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-v2.19.1-i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "90eb9c14f3241619cdd701a20b641d8f8838686e"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "62643fc9401d00b7294f3ae15cb738b18fb016dd75cbd46e9e1e9d67ff29fea0"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-v2.19.1-armv7l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75a0e7cd8864bc3640189997518ec307ebeb1296"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "ef8c3af69dbb2bf7e7cf3e7f3a9ea59abc78cac5b6bd55559999de7683fe33f6"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-v2.19.1-armv6l-linux-gnueabihf.tar.gz"
[[Glibc]]
arch = "aarch64"
git-tree-sha1 = "96eda59b7e06cf6260b405a02bbcbb61ec8916bc"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "5205fc270f7315ddb9694680c6ec8170e0384d7863ca8aa1ddb650c756e34285"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-v2.19.1-aarch64-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "829c27e62db28881f45ba59c6688a2fc6274cbde"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "daf7f48f66c6f69e6ab788a281b7143871e4f78f3d07bd738aa4736b27945f18"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-v2.19.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-build_log]]
arch = "x86_64"
git-tree-sha1 = "17a1141ec837ac89fd6a24134ad9097ba29d3a04"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "19f4f14ee3a3be6c698ee450e9306c4e71ca6bfa545980df00603237189f4243"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-build_log-v2.19.1-x86_64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "i686"
git-tree-sha1 = "6f9fcbf855f5f4f7186cbf5bb205a6a259403835"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "c100d914706e0c6b1114b6be67a36265bda52468a1272c0d1386c7acf8c0ab57"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-build_log-v2.19.1-i686-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0809b2ad70117421e644fbb36f69a1a5500d135c"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "50475aa6bf372ab3c248a2d09afae8c3c0057b81ae1f3aed39908212240450bd"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-build_log-v2.19.1-armv7l-linux-gnueabihf.tar.gz"
[[Glibc-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b38d33a91f8c2f255433fa0e520adb4395dad92b"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "ea144684af1d3cdb03a03801e0f2e4f3dc8d62fb36fac34b649aafe86195570c"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-build_log-v2.19.1-armv6l-linux-gnueabihf.tar.gz"
[[Glibc-build_log]]
arch = "aarch64"
git-tree-sha1 = "1a566eee5c9e60a2aff7992c014ed2a951b5d4d1"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "14791671591fac7484cfecc2ee3d22be0bd32332acb703d7e41e2786497f2d07"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-build_log-v2.19.1-aarch64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "c622ab601593745381804d1e1c804c4637100f0c"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "0de901a888bacb5e0944aca518f392962ac65466f43af99139dec5180e83450f"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-build_log-v2.19.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-extract_log]]
arch = "x86_64"
git-tree-sha1 = "279c97b9412da250ea2ef63a613ed3702f407cbe"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "c6e8c33bad3f88f1c6ea5773e145e9f329a75e428e01424c7ca8dc4378d6c6f7"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-extract_log-v2.19.1-x86_64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "i686"
git-tree-sha1 = "22022527f9ebee1b24d27400e331c433dc293cbb"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "6333fc3f2d166979a2d04f70293abd0c7c74fae15cfc1341c8df21d903e99a54"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-extract_log-v2.19.1-i686-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "77cebc0505df728eee9d395f30bd81066fdb630b"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "673c8e6db011fbb93d197a7215fe84fb0b6b8cbcdcc73181eacdb74466d1b9b8"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-extract_log-v2.19.1-armv7l-linux-gnueabihf.tar.gz"
[[Glibc-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "48203a249ed740079ef137b0e4385978ec99c134"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "865541b7c1965a748a0f0fdb5a3b7d2aec890fe36f945f545683ccec57883f4f"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-extract_log-v2.19.1-armv6l-linux-gnueabihf.tar.gz"
[[Glibc-extract_log]]
arch = "aarch64"
git-tree-sha1 = "9662404daab58b64592c42cc512a8d5ce22b8831"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "03d7a84286d110c16d51c264257c521fc9fcc0f83278da818d91bab8cc2a2ba9"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-extract_log-v2.19.1-aarch64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "7843aed8a649e685656f01e9ef7fda40339abd59"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "0748fbb21303cda594b366a6fa1d93be35b7986f81033b2b9e7ef3c2e32bac7d"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.1-GCC/Glibc-extract_log-v2.19.1-powerpc64le-linux-gnu.tar.gz"
