[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "883283764d9ef9ba27cc4a66e2fb851f19fb18d4"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "d7e1362069ae99f4d0a97e1dba2cd3f6c8a3f820bb371866613a2c374238fcb1"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.4-GCC/Glibc-v2.17.4-x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "c7864e28f1e515eb265b39beaa0a71f1e091d6db"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "ebd6d93ae2616ebe3595834c48559c697b609e96bf4d107650b853a25549c10a"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.4-GCC/Glibc-v2.17.4-i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "fa0918fac922aa5780f6fe485ca677617854a347"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "4156b541f72e1bfbdea23ab8d76d20ebf69fa482cd72c17ff0524875c80fb715"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.4-GCC/Glibc-v2.17.4-powerpc64le-linux-gnu.tar.gz"

[[Glibc-build_log]]
arch = "x86_64"
git-tree-sha1 = "af04e5cb90311599a0514601bb60adb8774ee879"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "1ab7b9c14752608d172c514c746fc46f619cdd8cfbc30ae5c2ee571a8ee0ebf7"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.4-GCC/Glibc-build_log-v2.17.4-x86_64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "i686"
git-tree-sha1 = "281f035e03b7799f771a219ea86b0b8a5200d48d"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "8c9a04238540ae234cdf4c2cc9a169943c00d267bc8c38c9a0df5a04b9a49a8e"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.4-GCC/Glibc-build_log-v2.17.4-i686-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "2b8e7ef9a1e92fdc3ff88fd380c2f6218854465c"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "c03d2976e1996bf2d02e98ce1b49e1b441bb695a43112fe5b11e1869469cc78b"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.4-GCC/Glibc-build_log-v2.17.4-powerpc64le-linux-gnu.tar.gz"

[[Glibc-extract_log]]
arch = "x86_64"
git-tree-sha1 = "9c6cd2c375b5d42cb17d37a6f98c6215928fe2f4"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "7ae8d74e8acd519bb4dccf572d0b9fd3c0128c15886e7e39117fe9da4f54eab6"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.4-GCC/Glibc-extract_log-v2.17.4-x86_64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "i686"
git-tree-sha1 = "517c22273a8e9a2cfb03a16a3dd0dc6d5e6ab45d"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "203971a5b5343b47f8c6747343159e35aeb830ff2010434c7d9df57c29235441"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.4-GCC/Glibc-extract_log-v2.17.4-i686-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "9a29aba7cad14f04687950c772b20a1f05377842"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "461aba35a935c3bace34b18cd702145e68684576353741ac2f3ee9dfb775a33f"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.4-GCC/Glibc-extract_log-v2.17.4-powerpc64le-linux-gnu.tar.gz"
