[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "af27d61804361d3ad4a8c0eccf0605f1a2da4b18"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "14490e8e1abfab618052d1ff13127b9b049b08c45d377802a92049ae6ebd3cb9"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "096457252f2a9f4bd2e6b40d575d14893ef2d3eb"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "1198bb5572bf59503e43c4e44a1fcc7a913c38603141f139b1cdc0d6590380ab"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "0468b1939ac1d6d2c8473cae203cbc9e46db9cfb"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "e3a79d9e39b99b4b748e66b3f340d04907136f165659c007332a29e4dcf0d6bd"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-build_log]]
arch = "x86_64"
git-tree-sha1 = "43c420f572254a26f69246a2f1cceec580ce0a1b"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "28881fc6a9a99c73b7146ac95a4c4f7314dbab02c8ca563d1702d4b5da5be404"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "i686"
git-tree-sha1 = "6a0fc6cc5ea1b6a6c5d31d4247986e2bfcd7481e"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "309a5f096e47e9fbac1fd0b54c8121d49f685f6459a094c6654107656c51ece0"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "a210ec2a4090bafa653453652edc11ceece45d89"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "5498bdeea1461c4a8113614e8e3dafaa138b1ba0c137611cd4a359a1f0a957b7"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f5e3ecd24b3aa2a72138a629b90bf15fe439b875"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "498116370e080dd91a9b084f8938fedce4c44ad40ea41fe40f4fa9eeefb83991"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "i686"
git-tree-sha1 = "2a8a8814d9b0b1253dc2301c498236e86d260e35"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "ed52c7f671060391b3c7dc8813e91274097248e54a6cd7028bdde697e2cd35dc"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "af5f47b9dae149d44c83b27057beeb203da324a5"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "f63d7070ec6bd356afb98aad4e87b629996c0ef2baeddb646017fa0044655658"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"
