[[Glibc]]
arch = "i686"
git-tree-sha1 = "d99e71a7a6e0a00bd0945302305ee7e3b2549296"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "db345d264015fe5d23c77f8da3591b4c95e7d93f1cbfd635b9b35d60be8466f5"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/Glibc-v2.17.0+1/Glibc.v2.17.0.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "9a79021a5ecfc26da6d3d36242bd88fbd39136fa"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "96b581387bc7980d760c6ee336d62618b97e11a563ef6283d02cf28d8e1fd991"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/Glibc-v2.17.0+1/Glibc.v2.17.0.powerpc64le-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "ecab10b14eacc84829d2328d13537ef591718dff"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "1d7c8a318aaab2c38e2c31e1c54015d717dc3fcfe87c1e21a744c7e7c804cdd5"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/Glibc-v2.17.0+1/Glibc.v2.17.0.x86_64-linux-gnu.tar.gz"
