[[Glibc]]
arch = "i686"
git-tree-sha1 = "c35f6a388255cd8abdb576d958d06cf688d8a488"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "667ae42f8e0142b254f2cff22f844646cad44a9875c7dfd534d8d2ea5fa67472"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/Glibc-v2.17.0+2/Glibc.v2.17.0.i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "acf237612615f31cffb1b409a7557532d69f8726"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "31b47ef7c8d26cd587b50b0ab169cb8e47c04f72123e3e23971a638341e3d573"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/Glibc-v2.17.0+2/Glibc.v2.17.0.powerpc64le-linux-gnu.tar.gz"
[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "5f6c8fb4081cb95411fc76fb664f99e36044cbdc"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "9745b2899588d40f89d659173d07791a352bbf97bb64e9f82f9900b5feaccb28"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/Glibc-v2.17.0+2/Glibc.v2.17.0.x86_64-linux-gnu.tar.gz"
