[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "d044964737883dd370c04b05043658146ed2fd79"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "d79853b527e1b6a50c030c0055b205557465e7107565c945cad8987ff06206e9"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "ffa9a3f1120d8574eeb0b5449a067913f847ec1e"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "0026ab7d81e8156e667f51241450e50a3e2f95ff023fbc42966946a218469e24"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "0ebe62694009e9cc6eb6b79f5d12a6dd78ff7fa0"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "b3322567dc0f70be20eabd57142087bd01dcf5a5eeb40f77f942b0a04fffbc74"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-build_log]]
arch = "x86_64"
git-tree-sha1 = "b21f841dd3591c3141336d38fc61ac48236e802e"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "cd5edc1060bdf700854c51a63ac08c62ff5569cd85f08f41bcb90457937b96f9"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "i686"
git-tree-sha1 = "d6100a97bb441e4c3d09720b480383f3bb446eb1"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "bbb04b635f3c25b8f8dc1befc5e1a7c138910c654cdde23ce0224db81528ae9f"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "1070349cd6b173254dbb81ea6b1eef00fc9e4b93"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "67e40c209a1eeb063024c1c52189eadc4bcade514ea1634b38dc906c8602d381"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-extract_log]]
arch = "x86_64"
git-tree-sha1 = "ae0f66cefd346873da369e455c50178667205ed8"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "8d13b2501657e32412709d566fb5246925299563f00222236a2d37c590449b0f"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "i686"
git-tree-sha1 = "d91908535228beb47e70af6dbaa1c6ea332dcf33"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "22874fd331fdcbc1333e81023b19a79357df892c368100a7551cddb60c29c46e"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "cc1a0adcd33f0d1b821261e1b88c19a2e8c56483"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "6811f41106fd273ef1381f3574092de111da1520f823b0fcf91826ddb2253528"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"
