[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "3c3fd6e9632c62ac23241f909507f10960b2279f"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "088aa23370194832f08faedb09076907e3057f94191506c8574cd06cd0086b24"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "3da1164abc23c404b2d588c82eb8bfef9d0125e5"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "d64adf7d88a6adb90dc7125312f263c8aa5fdeb965141f722f8c765ad7bd764d"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "13973345fd390ba71a5dd82600033caccd6f3436"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "049862b47f2e511bfb628e872f5492d2889aaf8374df9daf56d5d8bb3b074b8e"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-build_log]]
arch = "x86_64"
git-tree-sha1 = "131a36318d8a54290513a9e077fdd9d3dac355e7"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "02579a11988680d77938c2e822b8f7cc1f4274dd00a7316c3f428a4cf3a8253e"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "i686"
git-tree-sha1 = "d9fa05b04a59b3eefb439056f27865b7bcc9c745"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "ee7261cd3c54eb7bc967671ee824ac6ed6d1f82c66563e52a9e358215fad0e43"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "d6e7817faff756faf2b2db0c3f16b080025268bc"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "e6488f703da7f8c92c1a49d832108e433cac802f2a3c434f283ee052a0b00fea"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f00d2a74848f504b1c99882c8f25f8d2e27dfcc2"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "1934d7037d4a2245b167a7119e42f10f682de3042e3f2fcbadc692a4b7ce52d8"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "i686"
git-tree-sha1 = "86c459b226e08c4e66d2661bc09652ac66d54ac2"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "32ff1f275c2e3c9859592c9798858cfb3c9ff870294980699b030e47376a8990"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "2b5f01c0cc35ca530a5adc45a69e4406b7e6c971"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "be94909aa533b78313a908c394a712b2ff2dc1aa40ea3837a8a49ac3b9117f9b"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"
