[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "3959b59bf1814ba40b73ca2a779a7106daa9c7e5"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "57c8a4e043481f0f4c295effdff330c61b613e04f0cbb700e9e1a0e270f33c52"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCC/Glibc-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "0cc8d8dfdfb2c08d3aa424054ab38371f126ab2c"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "d5ea06657c95c2d1bffd9f2a5ef1ec2773dd54b46bca2d072499a6f0ff0130b9"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCC/Glibc-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "b23e5ddf09b5ce2b7447c7d504e51e3e14470116"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "18de2b6518652f644b55b4b7ea38fb57d47f414db4f0c3d1f3daa10130110545"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCC/Glibc-v2.17.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-build_log]]
arch = "x86_64"
git-tree-sha1 = "52b0ea59ef8bd78850e5a42c8da7cdc058a0eb39"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "1b70be573ad1e200018824184dfb1553762ad519326649819f1022e29216af49"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCC/Glibc-build_log-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "i686"
git-tree-sha1 = "01aac5c97c93e0cde78decac9073a5abc8684e13"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "90feb646282c60e342c723fecfaee2edd253a4e18a6c4c193d99225c7198f922"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCC/Glibc-build_log-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "4e8db7b396936987800732890d5aa45b195d3bf1"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "691377a51dd5cc61871b04f3f07279a2470464c248709ea7d57c4e29e5d534af"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCC/Glibc-build_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d80f9d39bcb83a5a0c5a9e90d898081ffc06725c"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "4fdc610b637b1f59d377a26a6c3ae0701893eb61ca65b693b7f968e0f93ed9eb"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCC/Glibc-extract_log-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "i686"
git-tree-sha1 = "f5252813df682b41b988c447e4c4585142250bb8"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "1b97e381f3d5ee6f3923a4cb8aa4bf93c559e4c87511412a513b2dc30c2ff162"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCC/Glibc-extract_log-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "298b3a5f5fe380f8776b599f04f45cff93596090"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "d449e17fb825698e5af1d2fed964066f431c8ee4d1a6dd58c67ff783a400daae"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCC/Glibc-extract_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"
