[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "60323bbf6cfd1024e91b285b5ebda1b24ac6c7ef"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "2157e0027e34a1ade62af813f0a9a54d672be0c49f5ba32ad766c1c1f3640ad3"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-v2.17.5-x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "4d5517291588c0ecb67be2e69b79924ffda503b4"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "f950c5f4074bd325e3e242629de301d66f771893eee37a5b9d916b9a4b84fe85"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-v2.17.5-i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "0fcb17b10c349529f51258311fd2fde739984c0d"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "00f9057112e59f2c0c71e09a8cef1aee4d870869cbff3fbb242bb22b3377cb60"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-v2.17.5-powerpc64le-linux-gnu.tar.gz"

[[Glibc-build_log]]
arch = "x86_64"
git-tree-sha1 = "8c856afba19ea69a4ffe73a9495d7101187c5671"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "a3fc6a4858d3ffd79296d47f51a82a31c1eb329d817275233fc99d5c0ced6119"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-build_log-v2.17.5-x86_64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "i686"
git-tree-sha1 = "f0efc73867650d2895e66a805ae709916bb06797"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "3f414e29b9df4a47d4f7085c7bb9ef8d7c77f0f2f3ac953f5bdab85356020992"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-build_log-v2.17.5-i686-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "2616c99a7264f9680cfdc9802d3003be31f4209b"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "7667b1607a16a47311f032bc5f6f9a736b6f7984696ea6604d00fdc5db3a4390"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-build_log-v2.17.5-powerpc64le-linux-gnu.tar.gz"

[[Glibc-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2375f7934994059d15b9e4bde62cfef16e8d6ad8"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "f83b34818c34f287be7ec774e9e6d7cb37fa1f971ecff49e6da7cbe3ccc973d8"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-extract_log-v2.17.5-x86_64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "i686"
git-tree-sha1 = "5359f21ab77741287bb6c85b865d349004f0ce4e"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "734a2cd376821bc2ff4611a06177f9b13f77bf516b74354607554e35548d1de9"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-extract_log-v2.17.5-i686-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "c44ac42930cee7cbeada662cea99c618bc44162c"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "4baea438d2303af8283abad0e7faa91646b65b24b279d902a46337a11df13301"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-extract_log-v2.17.5-powerpc64le-linux-gnu.tar.gz"
