[[Glibc]]
arch = "x86_64"
git-tree-sha1 = "382b91b0bda80667272d6f8c38579d3e015671a3"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "0a7ddafea7588df05a52d6cdbc705b6bf5321884bbd03199488535ca820a41c6"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCCBootstrap-x86_64-linux-gnu/Glibc-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc]]
arch = "i686"
git-tree-sha1 = "6e7599b06cdc729580d8af2c50189604a3741931"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "9f3e75390cf65670571ac7b31d41dac0fce43b4f0bd60a3d091bc479eb183fea"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCCBootstrap-x86_64-linux-gnu/Glibc-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc]]
arch = "powerpc64le"
git-tree-sha1 = "1ae61bb0442d63d89b8188866b95cab0f4c3cc0a"
libc = "glibc"
os = "linux"

    [[Glibc.download]]
    sha256 = "1533cfa917ebf9bdcb42a94233a37355dee37e2c79b5288f1e0bc5091511fa47"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCCBootstrap-x86_64-linux-gnu/Glibc-v2.17.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-build_log]]
arch = "x86_64"
git-tree-sha1 = "4d721ceef6aa88b04cd5b2721a9fa57aea0b76a6"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "0a0096c5f278c65a30017c654862130da83cdd1b81cf98ad01d88b82379dd4f1"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCCBootstrap-x86_64-linux-gnu/Glibc-build_log-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "i686"
git-tree-sha1 = "b62f37f6f357fd30512e76e2bfe19be2164c0df5"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "d7d1da589289811e53cffae1982b5b49aab6a93e13e46a7f9c83d04e6210f765"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCCBootstrap-x86_64-linux-gnu/Glibc-build_log-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "3d5847c757f5f2f4e55e1bb2b9aa03a001bb76da"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-build_log.download]]
    sha256 = "8ae9c02b09780dc04c4face3701d8011ac4f184a2330d9c518ab063b0cd040dc"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCCBootstrap-x86_64-linux-gnu/Glibc-build_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"

[[Glibc-extract_log]]
arch = "x86_64"
git-tree-sha1 = "3b2eb6c5cef30f536aa69398caa1a7015ddd63d4"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "5bb2eb91bd4e6e9378c790d394152287ce15caf767ca344d57fd2dcf0d79246b"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCCBootstrap-x86_64-linux-gnu/Glibc-extract_log-v2.17.1-x86_64-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "i686"
git-tree-sha1 = "5c98a9d35e4a8e1a24388e57d32666ad2a8f176b"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "0e9641ecad7a371caddbe944ca89df72a0da848872da67b94b99241f46b60247"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCCBootstrap-x86_64-linux-gnu/Glibc-extract_log-v2.17.1-i686-linux-gnu.tar.gz"
[[Glibc-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "4d399e45cdb5d9797fcaa46b291a6acc01a1ffe1"
lazy = true
libc = "glibc"
os = "linux"

    [[Glibc-extract_log.download]]
    sha256 = "0b8a7e93dc0e92dba2bdc1327d61e4e47f235a9388d38d04e1ea5bf6cd4aa317"
    url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1-GCCBootstrap-x86_64-linux-gnu/Glibc-extract_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"
