name = "Glibc"
version = "2.17.1"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:888824591dee1c5e0d66d4f2875c2dc583a6ff69"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:3a7d0e07d40f556f0f448e6563c9438649be7d1a5e9b4af950db70298bc22c5b"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:9407ffff83abc833318c84a3b3dcfe753f2fd8f2"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:fd775dfea8f9761095d1efecc8353908212c34b6f007a51eb5375de0cda36c10"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib64/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib64/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib64/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib64/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib64/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/bundled/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:80a38c4a91ada646628ab4bb3b615035d69dd5da"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:9d96b4f14a91ff0bc650eb922569bc737689d5ea93637dbaa15c4b3e24216cce"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-x86_64-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "i686-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:fcf3dc47d5440aadf18adf567e486187f8deb15b"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:15d9d86437d4d1a1c3813f74909ebd19145caf5d483fc0c9a24bf8d471c27153"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-i686-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c03d924bfd3597e6ddedf856e8dfa52025f7b45c"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:4783d9e653e14e0597f915151864f9305a18d20cb8eef1af62b65ec471a6b39d"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-i686-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/bundled/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:3cc36e7e58d97ba5932f23e896d17dcecea7a5de"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:26afe7b4699a86ed31ac0525fe788867132abe806b31e31da655c1ecda0bf94c"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-i686-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "powerpc64le-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:da1df5f9b8401fe7dbb4abfacf5ed61f29066e6b"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:e6ebed04e16cbfb547f9d7f07fd3c92536b80fd82fcf5c80cfa7e9c402002f55"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:2cc54dcec1d57d41313de3460e1c81fe9b1f8c33"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:0ff156c6755c8353aa3742c645fd55d993e1398ff768e9437a6c7db418ee39cc"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/bundled/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:759869191e5b1b16273e847e855d600df205b295"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:3d0489000366dfa9a5e9e9f5756ef4dc90a75a19401653d957bdc2b3dc0fd4fb"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-powerpc64le-linux-gnu.tar.gz"
