name = "Glibc"
version = "2.17.2"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:39eb163e99e6f0a8979a03715913d459fb3ab448"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:2e166bb76554b9a80a4024434cce4d421573d9d6553be0d200fef47e0cb5122c"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.2-GCC/Glibc-build_log-v2.17.2-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:ef6897d612289ba9cc2f8a5cb6c81fce2f4e7389"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:4f3046ee3342cb466381134556b9f3b86f086eddcdf33765db205f544474b9ff"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.2-GCC/Glibc-extract_log-v2.17.2-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib64/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib64/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib64/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib64/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib64/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:04ffc5395b59668d36dff6249ad72ca5a1eb47b8"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:a400ae981302c9b5f0c954c6925044cd814faef96c65ed541ffe1dd5f64fa293"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.2-GCC/Glibc-v2.17.2-x86_64-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "i686-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:508ef77aa04cadb7ab61fb12338dcf3860835597"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:d9bcc99058477cd223e4f735a63a28956d1a1acb554acda4e02f1d3210577540"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.2-GCC/Glibc-build_log-v2.17.2-i686-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:6a850b9db946a72d0722f5abfad84d73f2afd9e3"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:ebddd4d6debfb7981e1c8ab32154f9a0382383ed3480fb91177777eb1e49d444"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.2-GCC/Glibc-extract_log-v2.17.2-i686-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:cd60104b744564e20bebeeb2e4ca9b016f942bdd"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:df429d74aff39c7875d6f2c4427820544ec5f6e6f3030d4229274a9285e7f167"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.2-GCC/Glibc-v2.17.2-i686-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "powerpc64le-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:149b5bf4dbd095442866d4640397a817c3ecc9b1"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:b2efbd0c260d54d8a84194f28561ad3996ef885906938fee90bd5c54a71269fc"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.2-GCC/Glibc-build_log-v2.17.2-powerpc64le-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:968f400162a6325a03fe3871ea3fee72e50280bc"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:cb07c4f3598df549bb34a2844ac3bfc7e7d6213fc7817b7648cc2a14b03bc0f9"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.2-GCC/Glibc-extract_log-v2.17.2-powerpc64le-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:87ba6ce1fc9f4d071b6644a6d880dbd3dea57820"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:d3a48400060d5fceca6517d48022342548afe363521afa43db745aba0c23a080"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.2-GCC/Glibc-v2.17.2-powerpc64le-linux-gnu.tar.gz"
