name = "Glibc"
version = "2.17.1"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:18f10b49ef9495fc9d9055ab94f4d6f3b5449889"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:8093520024d59cda84baf11878372c444eec1d32fd443c6e4deb6b6019c76943"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:9407ffff83abc833318c84a3b3dcfe753f2fd8f2"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:b4748c0853d333052774052acf8c3a3ed3a3aa3eb5c6a4d33dd8a83238e92e67"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib64/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib64/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib64/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib64/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib64/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:448e83f8168f99c132b59151a0d2eaa3fe42fb3a"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:130d263b96e183a15c78508fb0b121421ce37c2865b01f3be5deba1ef09817ad"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-x86_64-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "i686-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:8475dbe84b06b9f33f5d32d1b30c9996de027a83"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:ea78062bd06d381f9af06befc6aa1c0ae964b7cff513749413f042ddd08b35b8"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-i686-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c03d924bfd3597e6ddedf856e8dfa52025f7b45c"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:686fc0bccac0baaa4e1cf930aa7f4651fcdabdf42079f7bb56c534c941fe5610"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-i686-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:4d0955779de021773611876cc0001ad95968d1ad"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:6b0b630d62a3574b26bd7701744be1403413021c2e42504c3cfb33828afb9454"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-i686-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "powerpc64le-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:cddec87539a2d96a6089fcf56eaa9ef57f729fcf"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:b1487bcffd3cd2052fc360ee7343a1007a3e91345dd17e9c2ecf38da7b28c5d0"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-build_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:2cc54dcec1d57d41313de3460e1c81fe9b1f8c33"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:6c6096c8f88799b301dcef21e29c9c4256457ee8605818f2682ebac2a32249cf"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-extract_log-v2.17.1-powerpc64le-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:0fc22d84c6b034735c8529e40f4946b633c24188"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:dfaf3bd70dd72baf95de028887b2a9ddc67a26c7daa2bf374958b22abafa55ae"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.1/Glibc-v2.17.1-powerpc64le-linux-gnu.tar.gz"
