name = "Glibc"
version = "2.17.6"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:c074ef856da5aecb60c2119a95e424c5b9bbe5b7"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:ade1d627f8025e8e72618ef3d73bc6b1e7345e542af268865ecf515ef732ab1d"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.6-GCC/Glibc-build_log-v2.17.6-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c94e35ec90d5f4e6f2662a51b061eef395bc2e1e"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:4a159381d64714130f02ad06cdaa6fd53750957be1c008afe4db0cc3137aa5b2"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.6-GCC/Glibc-extract_log-v2.17.6-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:851cd63854ff7c07088852f922b02c3db1981224"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:a2e2ad6ea18aef4405cfd44ca7535d825f21efb4b8fb9fda6032c510d85efcac"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.6-GCC/Glibc-v2.17.6-x86_64-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "i686-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:5de8740e87903f1e022ee6e97fdd1f3612ab2e64"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:01070d6840aca8c614dfb0f35a9794615aadda52ffcb8ff0de4b6bb92d42bc86"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.6-GCC/Glibc-build_log-v2.17.6-i686-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:8094ccbb06db6ea364b1e1ed50cbb2872a9356cb"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:cf72fb910b08579592d63fb8a62079738fa745fb422b647e2229d0b1727e5e99"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.6-GCC/Glibc-extract_log-v2.17.6-i686-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:acd4afe5ac5444ea29d80ff1dbd7aaab33e76100"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:aa24fe1ff1028809b073de3befdc5de8152febe8e7222f41a32c2bdaea978884"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.6-GCC/Glibc-v2.17.6-i686-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "powerpc64le-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:2119fc87e1a79b6ff67b73db4b2622d5f97f3459"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:fdf8ecd96e2fbaf320697ff7d078e7c73347178a0cb0d31b9c22db6f4ee18fa7"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.6-GCC/Glibc-build_log-v2.17.6-powerpc64le-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:a59626724cdd752e4d4decd28106a2eed0f53e3a"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:00d9eb97a72c71dcc01b0dd85063158d759b631df788a4188c9bb1968cf738d9"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.6-GCC/Glibc-extract_log-v2.17.6-powerpc64le-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:d139f197231e3df9e3d2c9e4c46646cdbe1ba141"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:def9ba780a736015df9edf40f58750647133df589e000c70683e7a5bf06acc17"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.6-GCC/Glibc-v2.17.6-powerpc64le-linux-gnu.tar.gz"
