name = "Glibc"
version = "2.17.5"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:8c856afba19ea69a4ffe73a9495d7101187c5671"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:a3fc6a4858d3ffd79296d47f51a82a31c1eb329d817275233fc99d5c0ced6119"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-build_log-v2.17.5-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:2375f7934994059d15b9e4bde62cfef16e8d6ad8"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:f83b34818c34f287be7ec774e9e6d7cb37fa1f971ecff49e6da7cbe3ccc973d8"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-extract_log-v2.17.5-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib64/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib64/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib64/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib64/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib64/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:60323bbf6cfd1024e91b285b5ebda1b24ac6c7ef"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:2157e0027e34a1ade62af813f0a9a54d672be0c49f5ba32ad766c1c1f3640ad3"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-v2.17.5-x86_64-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "i686-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:f0efc73867650d2895e66a805ae709916bb06797"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:3f414e29b9df4a47d4f7085c7bb9ef8d7c77f0f2f3ac953f5bdab85356020992"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-build_log-v2.17.5-i686-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:5359f21ab77741287bb6c85b865d349004f0ce4e"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:734a2cd376821bc2ff4611a06177f9b13f77bf516b74354607554e35548d1de9"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-extract_log-v2.17.5-i686-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:4d5517291588c0ecb67be2e69b79924ffda503b4"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:f950c5f4074bd325e3e242629de301d66f771893eee37a5b9d916b9a4b84fe85"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-v2.17.5-i686-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "powerpc64le-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:2616c99a7264f9680cfdc9802d3003be31f4209b"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:7667b1607a16a47311f032bc5f6f9a736b6f7984696ea6604d00fdc5db3a4390"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-build_log-v2.17.5-powerpc64le-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c44ac42930cee7cbeada662cea99c618bc44162c"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:4baea438d2303af8283abad0e7faa91646b65b24b279d902a46337a11df13301"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-extract_log-v2.17.5-powerpc64le-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:0fcb17b10c349529f51258311fd2fde739984c0d"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:00f9057112e59f2c0c71e09a8cef1aee4d870869cbff3fbb242bb22b3377cb60"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.5-GCC/Glibc-v2.17.5-powerpc64le-linux-gnu.tar.gz"
