name = "Glibc"
version = "2.17.3"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:9d6b35b40a58eb791b3b56787f30fbdd7d92d174"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:6d980cb0dfe5538fc7ae91f742b9f864089a6f9666c8544a26b6b39a9b562b44"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.3-GCC/Glibc-build_log-v2.17.3-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:295704644cb8775a55d726d3d36e57d49d18d730"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:c2fb0b5c462abf4963a6f95d23a59690d4e95238718cc8d66b384aabe50a895f"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.3-GCC/Glibc-extract_log-v2.17.3-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib64/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib64/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib64/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib64/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib64/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:77459190532b6e4681df151c625f28a0d83c059f"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:f7aa4d8a75d4016d3dec4da5ca894964dab5df88b9e0acbc5961d19cce9fe026"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.3-GCC/Glibc-v2.17.3-x86_64-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "i686-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:115f21b482d16ea6d353a14c4e1fd6d98ee75684"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:b641f4440803cdaf466a568d86c634f02ec2418ae5637827ce223322ddd67305"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.3-GCC/Glibc-build_log-v2.17.3-i686-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:d03769bc7b3fe5eb3659d37821709acb610d7d93"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:53b35f6e7d6200b92f95572fb2740cc89a78a58ecdff134b1f8e8e57b7ce7acc"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.3-GCC/Glibc-extract_log-v2.17.3-i686-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:8a6a4f5f96ea1740b8da240c09fd10b7221fae22"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:05b783a6f81e75024638a2e2131cfefa7b7badd62fb6643cff5205be6d5470b2"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.3-GCC/Glibc-v2.17.3-i686-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "powerpc64le-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:860d78dec80605ffd141c75055195f8dc5b8e9de"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:0f0e6d4c7f03417a1a56c907a28059bb5da8ee14262142d6ee3989322cd7bf9f"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.3-GCC/Glibc-build_log-v2.17.3-powerpc64le-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:493c5fc25faa007b7845e0fc2e5a77d19145d618"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:924a98a129b8b12fa962c533b5c20a5c2ae1b22adce3c33961f3879fb712c118"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.3-GCC/Glibc-extract_log-v2.17.3-powerpc64le-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:e62c4a66e1e5260fca213ec8c134cd6beb56a647"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:d52b5159396811aab68a1752e4619746ab799fd76060df50fe0bda024cd1c259"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.3-GCC/Glibc-v2.17.3-powerpc64le-linux-gnu.tar.gz"
