name = "Glibc"
version = "2.17.7"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:6f4de9edaeea674b87b8163717df5bd8bb39903f"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:0766dd8e5202a39af5051211b6a8a39b7aea5c30e9305c66bcc71cd518c9ab88"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-build_log-v2.17.7-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:5de0d2d5fa1ddd35d290d73571c0d8b6304dc268"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:4ac6bdd099283378bb34aa61fd0e1c5f1c6f856e2b61031a59867559c45bc2cc"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-extract_log-v2.17.7-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:857204c790397c17416a28e6dfb8dc4202ae3ae7"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:be582c8c824b9f25df350e6704e76b1c6a97ebbf89eb598784e907dc7eadc3af"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-v2.17.7-x86_64-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "i686-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:f25c148a97513e771e1dca067fc9c1b56d60969b"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:42dd3d2eb75b0734a96e9b6fd85d20067ede3384422fc7148f44f7fe60701ef4"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-build_log-v2.17.7-i686-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:db89abc905b15a8a03c083913e1b3580dbbdddf6"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:012455b06029c9a4c84cb41f5d5829a6287a98bc29af437d4c5ec7bd5cde6c7c"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-extract_log-v2.17.7-i686-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:0276e05729b40ed2585c410f4e5550190ebb19da"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:fe4a5b4b1b16703cbb4a53e770aaa647da77ef72b7f1125c69a199528256c4c3"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-v2.17.7-i686-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.17.0"
platform = "powerpc64le-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:3064b434c0ab2b3c78a219d454bff69c419e13cb"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:d52552042b237ce4fe6666fc9141e57937452fa40507256f3068aff998744cb4"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-build_log-v2.17.7-powerpc64le-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:47024253bf10104b1b53a50fc06116bc789dca20"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:6dc226aa76e915449d3b258fc6ad901dce36293f4d739aaea5e14e7fa976b008"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-extract_log-v2.17.7-powerpc64le-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.17.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.17.so"
    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.17.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.17.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.17.so"

    [[builds.sources]]
    treehash = "sha1:7891386e629b8a7b7c702c79f14f4ce5e37ee032"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.17.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbe067ca28f2e91c00b8b6b759b326aeedb6b074"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.17.0"

    [builds.artifact]
    treehash = "sha1:9732b83c697e8ac666473c9943bcbbf14c74c95d"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:7a6418a6f13a97a42a32c0aa1e826cdae12e80989ae2114233b59807a697a5d5"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.17.7-GCC/Glibc-v2.17.7-powerpc64le-linux-gnu.tar.gz"
