name = "Glibc"
version = "2.19.3"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.19.0"
platform = "x86_64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:01d7567bb2fab183fa0b5be45f43209d6ec86d87"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:09c12bc5de28889d0352e2b2fc735a7aad2bf5532469bd16d82c50e33703b228"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-build_log-v2.19.3-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:37848a7b6a67b87cfdf7af2b40984c8d9c59ce30"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:0a885ae0e61948ceca45dc51b2d981af05c8cfa070c635a44203f8f8783acce1"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-extract_log-v2.19.3-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.19.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.19.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.19.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.19.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.19.so"

    [[builds.sources]]
    treehash = "sha1:474cd7b41c1a9d48a9e6c8d5e7f606961e4f81e6"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.19.tar.xz"
    [[builds.sources]]
    treehash = "sha1:ff7aecceba8d4eabed40ec2f7b67ad4db8ebd92c"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.19.0"

    [builds.artifact]
    treehash = "sha1:8085c9b3cd4dd32e53fe07e6ed51733982bd4d13"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:57bfd353720d39199e172e34e7e96e53dd39ff32ff6e37b41b126f7ad349b6c6"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-v2.19.3-x86_64-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.19.0"
platform = "i686-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:90b49400b5646bebc5ee1c4e5e36b194021f2a47"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:364bd4903b7d50f2d386d28184522c4440171dd2534d926a98de679fb3d661b8"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-build_log-v2.19.3-i686-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:df27eea2a26147dade36280789df309ac6de671f"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:d89569f8a9793950a64496202b6dadff27d380fc5e016296ea7f1287b16f73a7"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-extract_log-v2.19.3-i686-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.19.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.19.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.19.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.19.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.19.so"

    [[builds.sources]]
    treehash = "sha1:474cd7b41c1a9d48a9e6c8d5e7f606961e4f81e6"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.19.tar.xz"
    [[builds.sources]]
    treehash = "sha1:ff7aecceba8d4eabed40ec2f7b67ad4db8ebd92c"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.19.0"

    [builds.artifact]
    treehash = "sha1:7501ea51625961171d0780da918ed4c952ede7c7"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:4e20025858e2f8eb3b7a63e7a96498e90266e5ab36785c15a81dc2b0fa9caf48"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-v2.19.3-i686-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.19.0"
platform = "armv7l-linux-gnueabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:b4b3ece1779053498b0859d9e742354225a49b6f"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:2ce4a95f99b3ae700b0862f41e4f89394aef13f506147b5795652e1dbaaf465b"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-build_log-v2.19.3-armv7l-linux-gnueabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:e0a745c7181aa24774a0f665d94c7eb1ca057ab6"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:00db1c9fbc299b6146f5bcb58b2eb16168d9eb86c0da433bdb29a781bc9bd647"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-extract_log-v2.19.3-armv7l-linux-gnueabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.19.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.19.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.19.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.19.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.19.so"

    [[builds.sources]]
    treehash = "sha1:474cd7b41c1a9d48a9e6c8d5e7f606961e4f81e6"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.19.tar.xz"
    [[builds.sources]]
    treehash = "sha1:ff7aecceba8d4eabed40ec2f7b67ad4db8ebd92c"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.19.0"

    [builds.artifact]
    treehash = "sha1:fad51ecaceff168ef8ae47e3d416c81570ced11e"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:d95daf91accb52511de66dca65e913691ceb9cb9e76de52286951cac1af7c160"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-v2.19.3-armv7l-linux-gnueabihf.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.19.0"
platform = "armv6l-linux-gnueabihf"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:c1581857275763d258c3e1fbdd86c7880a4aa013"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:23473ebb8df40dd1f491f887a82a0dc069f1eb05e5d1033660c699b3212895d0"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-build_log-v2.19.3-armv6l-linux-gnueabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:d4270c7c672030da93b6ab52dea53e5aa820800a"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:be71b55c3b80e0ddc56265267bae05526fe9e88ee29dcd350c9c6a1df2d6bbc2"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-extract_log-v2.19.3-armv6l-linux-gnueabihf.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.19.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.19.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.19.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.19.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.19.so"

    [[builds.sources]]
    treehash = "sha1:474cd7b41c1a9d48a9e6c8d5e7f606961e4f81e6"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.19.tar.xz"
    [[builds.sources]]
    treehash = "sha1:ff7aecceba8d4eabed40ec2f7b67ad4db8ebd92c"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.19.0"

    [builds.artifact]
    treehash = "sha1:4598d4d6441b9fd2be9b18d69503db14f9596fe1"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:1e853362a27d1c0258448ec3f8453279fe64ece5a9eb1529a516b91b418e6315"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-v2.19.3-armv6l-linux-gnueabihf.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.19.0"
platform = "aarch64-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:92ba338eac063eefd91c406da347e4e7eca8a651"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:663c7d7a5340a7e3ddb8f2a7af3e98d30fe16450f0976d22ac72b17daab534fc"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-build_log-v2.19.3-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:182274a93bced294b4dfe54836ae1c3c6355ed1f"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:c1fa7cf72be06818037307fabeab6059a888a2afb456badcd82175f9226e7604"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-extract_log-v2.19.3-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.19.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.19.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.19.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.19.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.19.so"

    [[builds.sources]]
    treehash = "sha1:474cd7b41c1a9d48a9e6c8d5e7f606961e4f81e6"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.19.tar.xz"
    [[builds.sources]]
    treehash = "sha1:ff7aecceba8d4eabed40ec2f7b67ad4db8ebd92c"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.19.0"

    [builds.artifact]
    treehash = "sha1:3826ac211f7875cc370b203942005ba43cc0895d"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:1a84402bf62207c0dcbe7a832a7b743b720bbdcda23c48489f52382591e82f84"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-v2.19.3-aarch64-linux-gnu.tar.gz"
[[builds]]
deps = []
name = "Glibc"
lazy = "false"
src_version = "2.19.0"
platform = "powerpc64le-linux-gnu"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:8705d787f08167f2c5c41fbcff3a3e7edcd2d805"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:5471d8894f850992a410e2a6fc0381fccb3224facca563ab8327bce71cb9c1d6"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-build_log-v2.19.3-powerpc64le-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:1001498b8c25b2078257c7e943dfd5483be27796"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:2f9365e1bb7e7a3faaf0b204b8a757ed5b5b98305aec8fa32074c74af2374f3b"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-extract_log-v2.19.3-powerpc64le-linux-gnu.tar.gz"

    [[builds.products]]
    deps = []
    name = "libm"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libm.so.6"
    type = "library"
    path = "lib/libm-2.19.so"
    [[builds.products]]
    deps = []
    name = "libpthread"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libpthread.so.0"
    type = "library"
    path = "lib/libpthread-2.19.so"
    [[builds.products]]
    deps = []
    name = "libc"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libc.so.6"
    type = "library"
    path = "lib/libc-2.19.so"
    [[builds.products]]
    deps = []
    name = "librt"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "librt.so.1"
    type = "library"
    path = "lib/librt-2.19.so"
    [[builds.products]]
    deps = []
    name = "libld"
    flags = ["RTLD_DEEPBIND", "RTLD_LAZY"]
    soname = "libdl.so.2"
    type = "library"
    path = "lib/libdl-2.19.so"

    [[builds.sources]]
    treehash = "sha1:474cd7b41c1a9d48a9e6c8d5e7f606961e4f81e6"
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.19.tar.xz"
    [[builds.sources]]
    treehash = "sha1:ff7aecceba8d4eabed40ec2f7b67ad4db8ebd92c"
    url = "/home/sabae/src/BB2/bootstrap/Glibc/patches-v2.19.0"

    [builds.artifact]
    treehash = "sha1:e84d95cbad5d46660fba2d0faddb24140267fcfd"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:cef1ccaaaa65d2af6d63ffa57128bb0c51674596f4ee9e010412a0f616dbaba2"
        url = "https://github.com/staticfloat/Glibc_jll.jl/releases/download/v2.19.3-GCC/Glibc-v2.19.3-powerpc64le-linux-gnu.tar.gz"
